const AltTeamLogo = [
    [
        '76ers_0.png',
        '76ers_1.png',
        '76ers_2.png',
        '76ers_3.png',
        '76ers_4.png',
        '76ers_5.png',
    ],
    [
        'Bucks_0.png',
        'Bucks_1.png',
        'Bucks_2.png',
        'Bucks_3.png'
    ],
    [
        'Bulls_0.png'
    ],
    [
        'Caveliers_0.png',
        'Caveliers_1.png',
        'Caveliers_2.png',
        'Caveliers_3.png',
        'Caveliers_4.png',
        'Caveliers_5.png',
        'Caveliers_6.png',
    ],
    [
        'Celtics_0.png',
        'Celtics_1.png',
        'Celtics_2.png',
        'Celtics_3.png',
        'Celtics_4.png',
        'Celtics_5.png',
        'Celtics_6.png',
    ],
    [
        'Clippers_0.png',
        'Clippers_1.png',
        'Clippers_2.png',
        'Clippers_3.png',
        'Clippers_4.png',
        'Clippers_5.png',
        'Clippers_6.png'
    ],
    [
        'Grizzlies_0.png',
        'Grizzlies_1.png',
        'Grizzlies_2.png'
    ],
    [
        'Hawks_0.png',
        'Hawks_1.png',
        'Hawks_2.png',
        'Hawks_3.png',
        'Hawks_4.png',
        'Hawks_5.png',
        'Hawks_6.png',
        'Hawks_7.png',
        'Hawks_8.png',
        'Hawks_9.png'
    ],
    [
        'Heat_0.png',
        'Heat_1.png',
        'Heat_2.png'
    ],
    [
        'Hornets_0.png',
        'Hornets_1.png',
        'Hornets_2.png',
        'Hornets_3.png',
        'Hornets_4.png',
        'Hornets_5.png',
        'Hornets_6.png'
    ],
    [
        'Jazz_0.png',
        'Jazz_1.png',
        'Jazz_2.png',
        'Jazz_3.png',
        'Jazz_4.png',
        'Jazz_5.png'
    ],
    [
        'Kings_0.png',
        'Kings_1.png',
        'Kings_2.png',
        'Kings_3.png',
        'Kings_4.png',
        'Kings_5.png',
        'Kings_6.png'
    ],
    [
        'Knicks_0.png',
        'Knicks_1.png',
        'Knicks_2.png',
        'Knicks_3.png',
        'Knicks_4.png',
        'Knicks_5.png',
        'Knicks_6.png',
        'Knicks_7.png'
    ],
    [
        'Lakers_0.png',
        'Lakers_1.png',
        'Lakers_2.png',
        'Lakers_3.png',
        'Lakers_4.png'
    ],
    [
        'Magic_0.png',
        'Magic_1.png',
        'Magic_2.png',
    ],
    [
        'Mavericks_0.png',
        'Mavericks_1.png',
        'Mavericks_2.png',
        'Mavericks_3.png'
    ],
    [
        'Nets_0.png',
        'Nets_1.png',
        'Nets_2.png',
        'Nets_3.png',
        'Nets_4.png',
        'Nets_5.png',
        'Nets_6.png'
    ],
    [
        'Nuggets_0.png',
        'Nuggets_1.png',
        'Nuggets_2.png',
        'Nuggets_3.png',
        'Nuggets_4.png',
        'Nuggets_5.png',
        'Nuggets_6.png',
        'Nuggets_7.png',
        'Nuggets_8.png',
        'Nuggets_9.png',
        'Nuggets_10.png'
    ],
    [
        'Pacers_0.png',
        'Pacers_1.png',
        'Pacers_2.png',
        'Pacers_3.png',
        'Pacers_4.png',
        'Pacers_5.png'
    ],
    [
        'Pelicans_0.png',
        'Pelicans_1.png',
        'Pelicans_2.png'
    ],
    [
        'Pistons_0.png',
        'Pistons_1.png',
        'Pistons_2.png',
        'Pistons_3.png',
        'Pistons_4.png',
        'Pistons_5.png',
        'Pistons_6.png',
        'Pistons_7.png',
        'Pistons_8.png'
    ],
    [
        'Raptors_0.png',
        'Raptors_1.png',
        'Raptors_2.png',
        'Raptors_3.png'
    ],
    [
        'Rockets_0.png',
        'Rockets_1.png',
        'Rockets_2.png',
        'Rockets_3.png',
        'Rockets_4.png',
        'Rockets_5.png'
    ],
    [
        'Spurs_0.png',
        'Spurs_1.png',
        'Spurs_2.png',
        'Spurs_3.png',
        'Spurs_4.png',
        'Spurs_5.png',
        'Spurs_6.png'
    ],
    [
        'Suns_0.png',
        'Suns_1.png',
        'Suns_2.png',
        'Suns_3.png'
    ],
    [
        'Thunder_0.png',
        'Thunder_1.png',
        'Thunder_2.png',
        'Thunder_3.png',
        'Thunder_4.png',
        'Thunder_5.png',
        'Thunder_6.png'
    ],
    [
        'Timberwolves_0.png',
        'Timberwolves_1.png',
        'Timberwolves_2.png',
        'Timberwolves_3.png'
    ],
    [
        'Trail Blazers_0.png',
        'Trail Blazers_1.png',
        'Trail Blazers_2.png',
        'Trail Blazers_3.png',
        'Trail Blazers_4.png',
        'Trail Blazers_5.png'
    ],
    [
        'Warriors_0.png',
        'Warriors_1.png',
        'Warriors_2.png',
        'Warriors_3.png',
        'Warriors_4.png',
        'Warriors_5.png',
        'Warriors_6.png',
        'Warriors_7.png',
        'Warriors_8.png',
        'Warriors_9.png'
    ],
    [
        'Wizards_0.png',
        'Wizards_1.png',
        'Wizards_2.png',
        'Wizards_3.png',
        'Wizards_4.png',
        'Wizards_5.png',
        'Wizards_6.png',
        'Wizards_7.png',
        'Wizards_8.png',
        'Wizards_9.png',
        'Wizards_10.png',
        'Wizards_11.png',
        'Wizards_12.png',
        'Wizards_13.png'
    ]
]

export default AltTeamLogo